import{a as L,S as w,i as g}from"./assets/vendor-BzajH6aU.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const b=document.querySelector(".loader"),S="46100469-a9a71a6d23d5188e64cb63582";new URLSearchParams({_limit:15,image_type:"photo",orientation:"horizontal",safesearch:!0});function m(l){b.style.display=l?"block":"none"}document.querySelector('input[name="search"]').value;async function h(l,a,i){if(l===""){iziToast.show({});return}try{const r=await L.get(`https://pixabay.com/api/?key=${S}&q=${l}&page=${a}&per_page=${i}`);return{hits:r.data.hits,total:r.data.total}}catch{}}const $=document.querySelector(".search-form"),d=document.querySelector(".gallery");let n;const u=15;let c=1,f=0;const p=new w(".gallery a");$.addEventListener("submit",async l=>{l.preventDefault();const a=document.querySelector('input[name="search"]').value.trim();d.innerHTML="",n&&n.remove();let i=0;c=1;try{const{hits:r,total:e}=await h(a,c,u);if(f=Math.ceil(e/u),console.log(f),r.length===0){g.show({title:"Error",message:"Sorry, your search query is incorrect. Please, change something there!",color:"red",position:"topCenter"});return}else{m(!0);const t=r.length;r.forEach(o=>{const s=document.createElement("li");s.classList.add("gallery-item"),s.innerHTML=`
          <a href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image">
          </a>
        `,d.appendChild(s);const y=s.querySelector(".gallery-image");y.onload=()=>{i++,console.log(i),i===t&&m(!1)}}),p.refresh()}r.length>=u&&(n=document.createElement("button"),n.textContent="Load more",n.classList.add("load-more"),d.after(n),n.addEventListener("click",async()=>{c++;const{hits:t}=await h(a,c,u);m(!0),t.forEach(o=>{const s=document.createElement("li");s.classList.add("gallery-item"),s.innerHTML=`
          <a href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image">
          </a>
        `,d.appendChild(s)}),p.refresh(),m(!1),c===f&&(g.show({title:"Infoline",message:"This is the last page",color:"green",position:"topCenter"}),n.remove())}))}catch{g.show({title:"Error",message:"Sorry, you have not written anything. Еnter a few letters to search!",color:"red",position:"topCenter"});return}finally{}});
//# sourceMappingURL=index.js.map
