import{a as S,S as b,i as p}from"./assets/vendor-BzajH6aU.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const q=document.querySelector(".loader"),$="46100469-a9a71a6d23d5188e64cb63582";new URLSearchParams({image_type:"photo",orientation:"horizontal",safesearch:!0});function d(n){q.style.display=n?"block":"none"}document.querySelector('input[name="search"]').value;async function h(n,l,r){if(n===""){iziToast.show({});return}try{const o=await S.get(`https://pixabay.com/api/?key=${$}&q=${n}&page=${l}&per_page=${r}`);return{hits:o.data.hits,total:o.data.total}}catch(o){console.error("Помилка при отриманні даних з Pixabay:",o),iziToast.show({title:"Помилка",message:"Виникла помилка при пошуку зображень. Будь ласка, спробуйте пізніше.",color:"red",position:"topCenter"})}}const v=document.querySelector(".search-form"),u=document.querySelector(".gallery");let s;const f=15;let m=1,y=0;const L=new b(".gallery a"),E=document.querySelector(".loader");v.addEventListener("submit",async n=>{n.preventDefault();const l=document.querySelector('input[name="search"]').value.trim();u.innerHTML="",s&&s.remove(),d&&d(!1);let r=0;m=1;try{const{hits:o,total:e}=await h(l,m,f);if(y=Math.ceil(e/f),console.log(y),o.length===0){p.show({title:"Error",message:"Sorry, ваш запит якийсь дивний. Напишіть щось зрозуміле",color:"red",position:"topCenter"});return}else{d(!0);const t=o.length;o.forEach(a=>{const i=document.createElement("li");i.classList.add("gallery-item"),i.innerHTML=`
          <a href="${a.largeImageURL}">
            <img src="${a.webformatURL}" alt="${a.tags}" class="gallery-image">
          </a>
        `,u.appendChild(i);const c=i.querySelector(".gallery-image");c.onload=()=>{r++,console.log(r),r===t&&d(!1)}}),L.refresh()}o.length>=f&&(s=document.createElement("button"),s.textContent="Load more",s.classList.add("load-more"),u.after(s)),s.addEventListener("click",async()=>{const t=document.querySelector(".load-more");t.parentNode.insertBefore(E,t),m++;const{hits:a}=await h(l,m,f);d(!0),a.forEach(c=>{const g=document.createElement("li");g.classList.add("gallery-item"),g.innerHTML=`
          <a href="${c.largeImageURL}">
            <img src="${c.webformatURL}" alt="${c.tags}" class="gallery-image">
          </a>
        `,u.appendChild(g),console.log(r);const w=g.querySelector(".gallery-image");r=0,w.onload=()=>{r++,console.log(r),console.log(a.length),r===a.length&&d(!1)}}),L.refresh();const i=document.querySelector(".gallery-item");if(i){const{height:c}=i.getBoundingClientRect();window.scrollBy({top:c*2,behavior:"smooth"})}m===y&&(p.show({title:"Infoline",message:"This is the last page",color:"green",position:"topCenter"}),s.remove())})}catch{p.show({title:"Error",message:"Вибачте, ви нічого не написали зрозумілою мовою. Введіть людське слово для пошуку!",color:"red",position:"topCenter"});return}finally{}});
//# sourceMappingURL=index.js.map
